Get bot online
JacobDevelopment/CourseBot pull request #1
Opened 2021-12-09 06:33 UTC by vinceTheProgrammer

Some basic code I wrote to get the bot online. My first ever pull request. Not sure if my code follows best practices. Feel free to optimize/clean up the code.

P.S. I just realized that I probably should have used the development branch instead of creating a new one 🤦‍♂️

2021-12-09 22:54 UTC, vinceTheProgrammer commented
I'm not sure if we need `.gradle/` and `build/`

There were merge conflicts, so I added those directories to the .gitignore and manually did `git rm` on these files:

- .gradle/6.7/executionHistory/executionHistory.bin
- .gradle/6.7/executionHistory/executionHistory.lock
- .gradle/6.7/fileHashes/fileHashes.bin
- .gradle/6.7/fileHashes/fileHashes.lock
- .gradle/buildOutputCleanup/buildOutputCleanup.lock
- .gradle/buildOutputCleanup/outputFiles.bin

2021-12-10 01:47 UTC, JacobDevelopment requested changes
Good, just need to change some minor things then we can push it. Adding those to the .gitignore is good, I forgot so no issues there.

2021-12-10 06:52 UTC, vinceTheProgrammer commented on src/main/java/io/jking/coursebot/Config.java
> +    public DataObject configObject;
Oh yeah, I forgot about that. This is good feedback for me in learning good practices in Java. I'll fix that right away.

2021-12-10 06:53 UTC, vinceTheProgrammer commented on src/main/java/io/jking/coursebot/Starter.java
> +        String token = (String) config.configObject.get("token");
Fair enough, I'll make the necessary changes.

2021-12-10 08:13 UTC, vinceTheProgrammer commented
I probably could have merged development into get-bot-online more efficiently, but I think I figured out how to merge everything correctly. You might still want to check it to make sure though.

2021-12-10 17:52 UTC, merged